//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MArchiveLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class staticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal staticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MArchiveLibrary.staticResources", typeof(staticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Development\Projects\marchive\MArchive.Web\moviePictures.
        /// </summary>
        public static string path_fullWebSiteImagePath {
            get {
                return ResourceManager.GetString("path_fullWebSiteImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isadm.
        /// </summary>
        public static string session_isUserAdmin {
            get {
                return ResourceManager.GetString("session_isUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchKeyword.
        /// </summary>
        public static string session_searchKeyword {
            get {
                return ResourceManager.GetString("session_searchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchParams.
        /// </summary>
        public static string session_searchParams {
            get {
                return ResourceManager.GetString("session_searchParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/moviePictures.
        /// </summary>
        public static string url_fullWebSiteImageUrl {
            get {
                return ResourceManager.GetString("url_fullWebSiteImageUrl", resourceCulture);
            }
        }
    }
}
