// <auto-generated />
namespace Authentication.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fb_g : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fb_g));
        
        string IMigrationMetadata.Id
        {
            get { return "201605041028213_fb_g"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
